### ISSUE TITLE
AddQueueTrackAsync throwing System.InvalidOperationException

### ISSUE THREAD

**Issue by Phill030** [ByteDev/ByteDev.Sonos#3]
So, everytime i try to play a song from Youtube/spotify it'll return an error which says "System.InvalidOperationException".
i always try it with `await sc.AddQueueTrackAsync("https://www.youtube.com/watch?v=9TYo8Xh3n_A");`
any idea why?

**Comment by ByteDev** [comment]
Do you have a full stack trace?

Though bear in mind the library does'nt currently support Spotify tracks and I've never tried YT. Playing tracks from a network device, like a NAS, should work though.

**Comment by Phill030** [comment]
so i would need to use for ex. "192.168.0.4\D:\Music\Music.mp3"?
